name: crypto_flutter_application
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  build_runner: ^2.4.11 
  hive_flutter: ^1.1.0 
  auto_route: ^8.2.0

  # talker_flutter: ^4.2.4

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  auto_route_generator: ^8.0.0



  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/bitcoin-logo.png
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

